name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: sudo apt-get -y -qq install upx
      - name: make
        run: make deps && make all
